[package]
name = "astromaticly/quarantine"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Cmdr = "evaera/cmdr@1.12.0"
Numberformatutil = "morgzov/numberformatutil@0.2.0"
fusion = "mattschrubb/fusion@1.2.5"
maid = "flamenco687/maid@3.2.2"
spring = "nightcycle/spring@1.0.0"
signal = "sleitnick/signal@2.0.1"
promise = "evaera/promise@4.0.0"
profileservice = "surnautica/profileservice@1.0.0"